"""`tools/backfill_archive.py` rebuilds the archive of PRs merged before `[paths] archive_dir`
existed, from the PR body, the PR comments and history.jsonl (AC-1 to AC-5); it depends on
nothing outside the standard library and revali, and the docs name it (AC-6)."""

import ast
import json
import os
import subprocess
import sys
import unittest

from tests.helpers import ROOT, RepoCase, _quote

SCRIPT = os.path.join(ROOT, "tools", "backfill_archive.py")

# A gh that answers `pr list -R <repo>` from a JSON file: {"<repo>": [pr, ...]} or
# {"<repo>": {"fail": "<message>"}}.
GH_STUB = """\
import json, os, sys
argv = sys.argv[1:]
data = json.load(open(os.environ["BACKFILL_FIXTURE"], encoding="utf-8"))
if argv[:2] != ["pr", "list"]:
    sys.exit("stub: unhandled %s" % argv)
answer = data[argv[argv.index("-R") + 1]]
if isinstance(answer, dict):
    sys.exit("gh: " + answer["fail"])
print(json.dumps(answer))
"""

BODY = (
    "---\r\ntitle: Add mul\r\nkind: feature\r\nauthor_model: m\r\n---\r\n\r\n## Request\r\n"
    "do it\r\n\r\n## Acceptance criteria\r\n- AC-1: works\r\n\r\n## revali status\r\n\r\n"
    "| round | verdict | model | cost |\r\n|---|---|---|---|\r\n| 1 | APPROVE | m | $1.00 |\r\n"
    "\r\nstage: `ready_to_merge`\r\n"
)
FULL_REVIEW = (
    "<!-- generated by revali -->\ntool: revali\nround: 1\nmodel_actual: m\n\n\n"
    "# Review round 1: CHANGES_REQUESTED\n\nfull text\n"
)
SUMMARY_REVIEW = (
    "<!-- generated by revali; summary only (non-private repository) -->\n\n"
    "# Review round 2: APPROVE\n\nmodel: m, cost: $0.50\n"
)
VALIDATION_1 = "## Validation 1: FAIL\n\nat: t1\n\n| step | exit |\n|---|---|\n| new_test | 1 |\n"
VALIDATION_2 = "## Validation 2: PASS\n\nat: t2\n"
OTHER = "Looks good to me, merging tomorrow.\n"


def pr(number, branch, body, comments=(), files=(), merged="2026-09-01T00:00:00Z"):
    return {
        "number": number,
        "title": "PR %d" % number,
        "headRefName": branch,
        "baseRefName": "main",
        "mergedAt": merged,
        "mergeCommit": {"oid": "abc%d" % number},
        "url": "https://example.invalid/pull/%d" % number,
        "body": body,
        "comments": [{"author": {"login": "me"}, "body": c} for c in comments],
        "files": [{"path": p} for p in files],
    }


def read(path):
    with open(path, "r", encoding="utf-8", newline="") as fh:
        return fh.read()


class BackfillCase(RepoCase):
    with_remote = False
    with_branch = False

    def setUp(self):
        super().setUp()
        self.stub = os.path.join(self.tmp, "gh_backfill_stub.py")
        with open(self.stub, "w", encoding="utf-8", newline="") as fh:
            fh.write(GH_STUB)
        self.fixture = os.path.join(self.tmp, "prs.json")
        os.environ["REVALI_GH_CMD"] = "%s %s" % (_quote(sys.executable), _quote(self.stub))
        os.environ["BACKFILL_FIXTURE"] = self.fixture
        self.prs(
            {
                "me/proj": [
                    pr(
                        1,
                        "feature/mul",
                        BODY,
                        [FULL_REVIEW, VALIDATION_1, SUMMARY_REVIEW, OTHER, VALIDATION_2],
                        ["revali/x.py", "tests/test_review_mul.py", "tests/test_mine.py"],
                    ),
                    pr(2, "chore/plain", "Bumped a version.\n"),
                    pr(
                        3, "fix/no-table", "---\ntitle: No table\nkind: fix\n---\n\n## Request\nx\n"
                    ),
                ]
            }
        )
        rows = [
            {"repo": "me/proj", "branch": "feature/mul", "stage": "review", "rounds": 1},
            {"repo": "me/proj", "branch": "other", "stage": "merged"},
            {"repo": "me/proj", "branch": "feature/mul", "stage": "merged", "rounds": 2},
            {"repo": "you/proj", "branch": "feature/mul", "stage": "merged"},
        ]
        with open(os.path.join(self.home, "history.jsonl"), "w", encoding="utf-8") as fh:
            fh.write("".join(json.dumps(r) + "\n" for r in rows))

    def prs(self, data):
        with open(self.fixture, "w", encoding="utf-8") as fh:
            json.dump(data, fh)

    def user_config(self, text):
        with open(os.path.join(self.home, "config.toml"), "w", encoding="utf-8") as fh:
            fh.write(text)

    def run_tool(self, *args):
        res = subprocess.run(
            [sys.executable, SCRIPT] + list(args),
            capture_output=True,
            text=True,
            encoding="utf-8",
            cwd=self.tmp,
        )
        return res.returncode, res.stdout, res.stderr

    def dest(self, name="1-feature__mul", root=None):
        return os.path.join(root or os.path.join(self.home, "archive"), "me__proj", name)


class Rebuild(BackfillCase):
    def test_every_revali_pr_gets_a_directory_under_the_default_root(self):
        # AC-1: root = [paths] archive_dir as merge resolves it (defaults, under REVALI_HOME)
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest()), out)
        self.assertTrue(os.path.isdir(self.dest("3-fix__no-table")), out)
        self.assertFalse(os.path.isdir(self.dest("2-chore__plain")))
        self.assertIn("#2 not a revali PR, skipped", out)
        self.assertIn("me/proj: 2 rebuilt, 0 already there, 1 not revali", out)

    def test_the_files_of_a_rebuilt_directory(self):
        # AC-2
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        d = self.dest()
        self.assertEqual(
            sorted(os.listdir(d)),
            [
                "README.md",
                "change.md",
                "comment-1.md",
                "history.jsonl",
                "review-1.md",
                "review-2.md",
                "tests.md",
            ],
        )
        change = read(os.path.join(d, "change.md"))
        self.assertTrue(change.startswith("---\ntitle: Add mul\n"))
        self.assertTrue(change.endswith("- AC-1: works\n"))
        self.assertNotIn("revali status", change)
        self.assertEqual(read(os.path.join(d, "review-1.md")), FULL_REVIEW)
        self.assertEqual(read(os.path.join(d, "review-2.md")), SUMMARY_REVIEW)
        tests = read(os.path.join(d, "tests.md"))
        self.assertTrue(tests.startswith("<!-- rebuilt from the PR comments"))
        self.assertLess(tests.index("## Validation 1: FAIL"), tests.index("## Validation 2: PASS"))
        self.assertIn("| new_test | 1 |", tests)
        self.assertEqual(read(os.path.join(d, "comment-1.md")), OTHER)
        history = read(os.path.join(d, "history.jsonl")).splitlines()
        self.assertEqual([json.loads(h)["rounds"] for h in history], [1, 2])
        readme = read(os.path.join(d, "README.md"))
        for text in (
            "https://example.invalid/pull/1",
            "PR 1",
            "`feature/mul` into `main`",
            "2026-09-01T00:00:00Z",
            "abc1",
            "- `tests/test_review_mul.py`",
            "response-<n>.md",
            "| 1 | APPROVE | m | $1.00 |",
        ):
            self.assertIn(text, readme, text)
        self.assertNotIn("tests/test_mine.py", readme)
        for name in os.listdir(d):
            self.assertNotIn("\r", read(os.path.join(d, name)), name)

    def test_a_pr_without_table_comments_or_history(self):
        # AC-2: change.md is the whole body; no tests.md, no history.jsonl
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        d = self.dest("3-fix__no-table")
        self.assertEqual(sorted(os.listdir(d)), ["README.md", "change.md"])
        self.assertEqual(
            read(os.path.join(d, "change.md")),
            "---\ntitle: No table\nkind: fix\n---\n\n## Request\nx\n",
        )
        self.assertIn("- (none in this PR)", read(os.path.join(d, "README.md")))

    def test_the_user_archive_dir_and_the_flag(self):
        # AC-1: the user file moves the root; --archive-dir wins over it
        self.user_config('[paths]\narchive_dir = "kept"\n')
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest(root=os.path.join(self.home, "kept"))), out)
        self.assertFalse(os.path.isdir(os.path.join(self.home, "archive")))
        elsewhere = os.path.join(self.tmp, "else where")
        code, out, err = self.run_tool("me/proj", "--archive-dir", elsewhere)
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest(root=elsewhere)), out)

    def test_several_repositories_in_one_call(self):
        # AC-1
        self.prs({"me/proj": [pr(1, "feature/mul", BODY)], "me/other": [pr(4, "a/b", BODY)]})
        code, out, err = self.run_tool("me/proj", "me/other")
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest()))
        self.assertTrue(os.path.isdir(os.path.join(self.home, "archive", "me__other", "4-a__b")))
        self.assertIn("total: 2 directories", out)


class Rerun(BackfillCase):
    def test_an_existing_directory_is_left_alone(self):
        # AC-3: the archive `revali merge` wrote survives; a second run is a no-op
        d = self.dest()
        os.makedirs(d)
        with open(os.path.join(d, "state.json"), "w", encoding="utf-8") as fh:
            fh.write("{}")
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertEqual(os.listdir(d), ["state.json"])
        self.assertIn("#1 exists, skipped", out)
        self.assertIn("me/proj: 1 rebuilt, 1 already there, 1 not revali", out)
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertIn("me/proj: 0 rebuilt, 2 already there, 1 not revali", out)
        self.assertIn("total: 0 directories", out)

    def test_dry_run_writes_nothing(self):
        # AC-4
        code, dry, err = self.run_tool("me/proj", "--dry-run")
        self.assertEqual(code, 0, err)
        self.assertFalse(os.path.exists(os.path.join(self.home, "archive")))
        self.assertIn("(dry run)", dry)
        self.assertIn("total: 2 directories would be created", dry)
        code, wet, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        lines = lambda text: [ln for ln in text.splitlines() if ln.startswith("  #")]  # noqa: E731
        self.assertEqual(lines(dry), lines(wet))
        self.assertIn("review-1.md, review-2.md, tests.md", lines(dry)[0])


class Failures(BackfillCase):
    def test_an_empty_root_is_an_error(self):
        # AC-5
        self.user_config('[paths]\narchive_dir = ""\n')
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 1, out)
        self.assertIn("archive_dir is empty", err)
        self.assertEqual(os.listdir(self.home), ["config.toml", "history.jsonl"])
        code, out, err = self.run_tool("me/proj", "--archive-dir", os.path.join(self.tmp, "a"))
        self.assertEqual(code, 0, err)

    def test_a_failing_gh_stops_that_repository_and_keeps_the_earlier_ones(self):
        # AC-5
        self.prs({"me/proj": [pr(1, "feature/mul", BODY)], "me/gone": {"fail": "not found"}})
        code, out, err = self.run_tool("me/proj", "me/gone")
        self.assertEqual(code, 1, out)
        self.assertIn("not found", err)
        self.assertIn("me/gone", err)
        self.assertTrue(os.path.isdir(self.dest()))
        self.assertFalse(os.path.isdir(os.path.join(self.home, "archive", "me__gone")))


class RoundOneFindings(BackfillCase):
    def test_a_listing_that_reaches_the_limit_is_refused(self):
        # AC-5 (round 1 F1): gh stops at --limit, newest first; the oldest PRs may be missing
        code, out, err = self.run_tool("me/proj", "--limit", "3")
        self.assertEqual(code, 1, out + err)
        self.assertEqual(len(err.strip().splitlines()), 1, err)
        self.assertIn("--limit", err)
        self.assertFalse(os.path.exists(os.path.join(self.home, "archive")))
        code, out, err = self.run_tool("me/proj", "--limit", "4")
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest()))

    def test_a_history_line_that_does_not_parse_is_dropped(self):
        # AC-2, AC-5 (round 1 F2): read the way revali reads it, no traceback
        path = os.path.join(self.home, "history.jsonl")
        with open(path, "a", encoding="utf-8") as fh:
            fh.write('{"repo": "me/proj", "branch": "feature/mul", "stage": "merg')
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        history = read(os.path.join(self.dest(), "history.jsonl")).splitlines()
        self.assertEqual([json.loads(h)["rounds"] for h in history], [1, 2])

    def test_the_user_history_path_is_honoured(self):
        # AC-2 (round 1 F4): history_path from the user file, as revali resolves it
        moved = os.path.join(self.tmp, "runs.jsonl")
        os.replace(os.path.join(self.home, "history.jsonl"), moved)
        self.user_config("history_path = %s\n" % json.dumps(moved.replace("\\", "/")))
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isfile(os.path.join(self.dest(), "history.jsonl")), out)

    def test_the_root_ignores_the_revali_checkouts_project_file(self):
        # AC-1 (round 1 F3): defaults and the user file only; module-level check, the
        # checkout's revali.toml is not edited by a test
        sys.path.insert(0, os.path.join(ROOT, "tools"))
        try:
            import backfill_archive
        finally:
            sys.path.pop(0)
        self.assertEqual(backfill_archive.default_root(None), os.path.join(self.home, "archive"))
        self.user_config('[paths]\narchive_dir = "kept"\n')
        from revali.config import load_user_config

        self.assertEqual(
            backfill_archive.default_root(load_user_config()), os.path.join(self.home, "kept")
        )

    def test_a_suffixed_archive_counts_as_existing(self):
        # follow-up: merge wrote <pr>-<branch>-<timestamp> for a taken name
        suffixed = self.dest() + "-20260907-120000"
        os.makedirs(suffixed)
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertFalse(os.path.exists(self.dest()))
        self.assertIn("#1 exists, skipped: %s" % suffixed, out)

    def test_two_comments_for_one_round_are_reported(self):
        # follow-up: a retried post; the later comment wins and the output says so
        self.prs(
            {
                "me/proj": [
                    pr(
                        1,
                        "feature/mul",
                        BODY,
                        [FULL_REVIEW, SUMMARY_REVIEW.replace("round 2", "round 1")],
                    )
                ]
            }
        )
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertIn("#1: two comments for review-1.md; the later one kept", out)
        self.assertIn("# Review round 1: APPROVE", read(os.path.join(self.dest(), "review-1.md")))


class DependenciesAndDocs(unittest.TestCase):
    def test_the_script_imports_only_the_standard_library_and_revali(self):
        # AC-6
        tree = ast.parse(read(SCRIPT))
        names = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names.update(a.name.split(".")[0] for a in node.names)
            elif isinstance(node, ast.ImportFrom):
                names.add((node.module or "").split(".")[0])
        for name in names:
            self.assertTrue(name == "revali" or name in sys.stdlib_module_names, name)

    def test_the_docs_name_the_tool(self):
        # AC-6
        readme = read(os.path.join(ROOT, "README.md"))
        development = readme.split("\n## Development\n", 1)[1]
        self.assertIn("python tools/backfill_archive.py", development)
        files = read(os.path.join(ROOT, "docs", "files.md"))
        archive_row = [ln for ln in files.splitlines() if "archive of a merged branch" in ln]
        self.assertEqual(len(archive_row), 1, archive_row)
        self.assertIn("[`tools/backfill_archive.py`](../tools/backfill_archive.py)", archive_row[0])


if __name__ == "__main__":
    unittest.main()
