"""Review of feature/backfill-archive: `tools/backfill_archive.py` rebuilds, from the PR body,
the PR comments and history.jsonl, the directory `revali merge` would have archived for PRs
merged before `[paths] archive_dir` existed.

AC-1 the layout under the resolved root (defaults under REVALI_HOME, the user file, the flag),
a PR without a change.md body is skipped and named, several repositories per call;
AC-2 the files of a rebuilt directory and their content, CRLF converted, nothing optional
written when there is nothing to put in it;
AC-3 an existing directory is left alone and reported, a rerun is a no-op with exit 0;
AC-4 --dry-run prints the same per-PR lines and writes nothing;
AC-5 an empty root, a failing or missing gh and a listing that reaches --limit exit 1 with one
line on stderr, nothing written for that repository, earlier repositories kept;
AC-6 the import list (stdlib and revali only); the wording of README and docs is documentation.

Round 2 adds the --limit refusal, the missing gh, a history line that does not parse, the
user's history_path, a project file that must not move the root, the suffixed directory
`merge` writes for a taken name, and two comments for one review round.

Black-box: the script runs as a subprocess with a private gh stub behind REVALI_GH_CMD (the
seam the AC names) and the isolated REVALI_HOME RepoCase provides."""

import ast
import json
import os
import subprocess
import sys
import unittest

from tests.helpers import ROOT, RepoCase, _quote

SCRIPT = os.path.join(ROOT, "tools", "backfill_archive.py")

# gh stub: answers `pr list -R <repo> ...` from BACKFILL_REVIEW_FIXTURE, a JSON file mapping
# "<owner>/<name>" to a list of PRs or to {"fail": "<stderr text>"}.
GH_STUB = """\
import json, os, sys
argv = sys.argv[1:]
if argv[:2] != ["pr", "list"] or "-R" not in argv:
    sys.exit("stub: unexpected call %r" % (argv,))
if "--state" in argv and argv[argv.index("--state") + 1] != "merged":
    sys.exit("stub: expected --state merged")
with open(os.environ["BACKFILL_REVIEW_FIXTURE"], encoding="utf-8") as fh:
    data = json.load(fh)
answer = data.get(argv[argv.index("-R") + 1])
if answer is None:
    sys.exit("gh: repository not in fixture")
if isinstance(answer, dict):
    sys.exit(answer["fail"])
print(json.dumps(answer))
"""

CHANGE_LINES = [
    "---",
    "title: Add mul",
    "kind: feature",
    "author_model: claude-x",
    "---",
    "",
    "## Request",
    "(withheld: public repository)",
    "",
    "## Goal",
    "mul exists",
    "",
    "## Acceptance criteria",
    "- AC-1: mul(3, 4) == 12",
]
STATUS_LINES = [
    "",
    "## revali status",
    "",
    "| round | verdict | model | cost |",
    "|---|---|---|---|",
    "| 1 | CHANGES_REQUESTED | claude-y | $1.20 |",
    "| 2 | APPROVE | claude-y | $0.80 |",
    "",
    "stage: `merged`",
]
BODY_CRLF = "\r\n".join(CHANGE_LINES + STATUS_LINES) + "\r\n"
BODY_PLAIN = "---\ntitle: Plain fix\nkind: fix\nauthor_model: m\n---\n\n## Request\nfix it\n"

REVIEW_1 = (
    "<!-- generated by revali -->\n"
    "tool: revali\n"
    "round: 1\n"
    "model_actual: claude-y\n"
    "cost_usd: 1.2\n"
    "\n"
    "# Review round 1: CHANGES_REQUESTED\n"
    "\n"
    "The product is off by one.\n"
    "\n"
    "## Findings\n"
    "\n"
    "- F1 high: wrong result\n"
)
REVIEW_2_CRLF = (
    "<!-- generated by revali; summary only (non-private repository) -->\r\n"
    "\r\n"
    "# Review round 2: APPROVE\r\n"
    "\r\n"
    "model: claude-y, cost: $0.80\r\n"
)
VALIDATION_1 = (
    "## Validation 1: FAIL\n\nat: 2026-08-30T10:00:00+0800\n\n"
    "| step | exit |\n|---|---|\n| new_test | 1 |\n"
)
VALIDATION_2 = (
    "## Validation 2: PASS\n\nat: 2026-08-30T11:00:00+0800\n\n| step | exit |\n|---|---|\n"
)
CHATTER = "Thanks, I will look at this tomorrow.\n"
WITHHELD = (
    "revali withheld this comment: it looked like it contained a credential (aws-key). "
    "The full text is in .revali/ on the author's machine.\n"
)


def pr(number, branch, body, comments=(), files=(), title=None):
    return {
        "number": number,
        "title": title or "PR %d title" % number,
        "headRefName": branch,
        "baseRefName": "main",
        "mergedAt": "2026-08-30T12:00:%02dZ" % number,
        "mergeCommit": {"oid": "c0ffee%02d" % number},
        "url": "https://example.invalid/me/proj/pull/%d" % number,
        "body": body,
        "comments": [{"author": {"login": "me"}, "body": c} for c in comments],
        "files": [{"path": p} for p in files],
    }


def read(path):
    with open(path, "r", encoding="utf-8", newline="") as fh:
        return fh.read()


def files_under(root):
    found = []
    for base, _dirs, names in os.walk(root):
        for name in names:
            found.append(os.path.relpath(os.path.join(base, name), root).replace("\\", "/"))
    return sorted(found)


class BackfillCase(RepoCase):
    with_remote = False
    with_branch = False

    def setUp(self):
        super().setUp()
        self.stub = os.path.join(self.tmp, "gh_review_stub.py")
        with open(self.stub, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(GH_STUB)
        self.fixture = os.path.join(self.tmp, "review prs.json")
        os.environ["REVALI_GH_CMD"] = "%s %s" % (_quote(sys.executable), _quote(self.stub))
        os.environ["BACKFILL_REVIEW_FIXTURE"] = self.fixture
        self.prs({"me/proj": self.default_prs()})
        self.history(
            [
                {"repo": "me/proj", "branch": "feature/mul", "stage": "review", "rounds": 1},
                {"repo": "me/proj", "branch": "fix/plain", "stage": "merged", "rounds": 1},
                {"repo": "other/proj", "branch": "feature/mul", "stage": "merged", "rounds": 9},
                {"repo": "me/proj", "branch": "feature/mul", "stage": "merged", "rounds": 2},
            ]
        )

    def default_prs(self):
        return [
            pr(
                7,
                "feature/mul",
                BODY_CRLF,
                [REVIEW_1, VALIDATION_1, CHATTER, REVIEW_2_CRLF, WITHHELD, VALIDATION_2],
                ["src/calc.py", "tests/test_review_mul.py", "tests/test_calc.py"],
                title="Add mul",
            ),
            pr(8, "chore/bump", "Bump the version.\r\n"),
            pr(9, "fix/plain", BODY_PLAIN),
        ]

    def prs(self, data):
        with open(self.fixture, "w", encoding="utf-8") as fh:
            json.dump(data, fh)

    def history(self, rows):
        with open(os.path.join(self.home, "history.jsonl"), "w", encoding="utf-8") as fh:
            fh.write("".join(json.dumps(r) + "\n" for r in rows))

    def user_config(self, text):
        with open(os.path.join(self.home, "config.toml"), "w", encoding="utf-8") as fh:
            fh.write(text)

    def run_tool(self, *args, env=None):
        res = subprocess.run(
            [sys.executable, SCRIPT] + list(args),
            capture_output=True,
            text=True,
            encoding="utf-8",
            cwd=self.tmp,
            env=env,
        )
        return res.returncode, res.stdout, res.stderr

    def archive(self):
        return os.path.join(self.home, "archive")

    def dest(self, name="7-feature__mul", root=None):
        return os.path.join(root or self.archive(), "me__proj", name)

    def pr_lines(self, out, number):
        return [ln for ln in out.splitlines() if "#%d" % number in ln]


class Layout(BackfillCase):
    """AC-1"""

    def test_one_directory_per_revali_pr_under_the_default_root(self):
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertNotIn("Traceback", err)
        self.assertTrue(os.path.isdir(self.dest()), out)
        self.assertTrue(os.path.isdir(self.dest("9-fix__plain")), out)
        self.assertEqual(sorted(os.listdir(self.dest(""))), ["7-feature__mul", "9-fix__plain"])
        self.assertEqual(os.listdir(self.archive()), ["me__proj"])
        self.assertFalse(os.path.isdir(self.dest("8-chore__bump")))

    def test_a_pr_whose_body_is_not_a_change_md_is_skipped_and_named(self):
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        lines = self.pr_lines(out, 8)
        self.assertEqual(len(lines), 1, out)
        self.assertIn("skipped", lines[0])
        self.assertNotIn("8-chore__bump", out)

    def test_a_body_with_front_matter_but_no_title_is_not_a_revali_pr(self):
        self.prs({"me/proj": [pr(5, "x/y", "---\nlayout: post\n---\ntext\n")]})
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertFalse(os.path.exists(self.archive()))
        self.assertIn("skipped", "".join(self.pr_lines(out, 5)))

    def test_the_user_archive_dir_is_relative_to_revali_home(self):
        self.user_config('[paths]\narchive_dir = "kept/here"\n')
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        root = os.path.join(self.home, "kept", "here")
        self.assertTrue(os.path.isdir(self.dest(root=root)), out)
        self.assertTrue(os.path.isdir(self.dest("9-fix__plain", root=root)), out)
        self.assertFalse(os.path.isdir(self.archive()))

    def test_the_flag_wins_over_the_user_file(self):
        self.user_config('[paths]\narchive_dir = "from-user"\n')
        elsewhere = os.path.join(self.tmp, "shared archive")
        code, out, err = self.run_tool("me/proj", "--archive-dir", elsewhere)
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest(root=elsewhere)), out)
        self.assertFalse(os.path.isdir(os.path.join(self.home, "from-user")))
        self.assertFalse(os.path.isdir(self.archive()))

    def test_several_repositories_in_one_call(self):
        self.prs(
            {
                "me/proj": [pr(7, "feature/mul", BODY_CRLF)],
                "you/tool": [pr(2, "feat/a-b", BODY_PLAIN), pr(3, "no", "plain body\n")],
            }
        )
        code, out, err = self.run_tool("me/proj", "you/tool")
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest()), out)
        self.assertTrue(os.path.isdir(os.path.join(self.archive(), "you__tool", "2-feat__a-b")))
        self.assertEqual(sorted(os.listdir(self.archive())), ["me__proj", "you__tool"])
        self.assertEqual(os.listdir(os.path.join(self.archive(), "you__tool")), ["2-feat__a-b"])


class Content(BackfillCase):
    """AC-2"""

    def rebuilt(self):
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        return self.dest()

    def test_the_set_of_files(self):
        d = self.rebuilt()
        self.assertEqual(
            files_under(d),
            [
                "README.md",
                "change.md",
                "comment-1.md",
                "comment-2.md",
                "history.jsonl",
                "review-1.md",
                "review-2.md",
                "tests.md",
            ],
        )

    def test_change_md_is_the_body_up_to_the_status_table_with_lf(self):
        change = read(os.path.join(self.rebuilt(), "change.md"))
        self.assertNotIn("\r", change)
        self.assertNotIn("revali status", change)
        self.assertNotIn("| 1 | CHANGES_REQUESTED", change)
        self.assertEqual(change.rstrip("\n"), "\n".join(CHANGE_LINES))

    def test_review_files_map_the_full_and_the_summary_comment_to_their_round(self):
        d = self.rebuilt()
        self.assertEqual(read(os.path.join(d, "review-1.md")), REVIEW_1)
        summary_lf = REVIEW_2_CRLF.replace("\r\n", "\n")
        self.assertEqual(read(os.path.join(d, "review-2.md")), summary_lf)

    def test_tests_md_holds_every_validation_in_posting_order_behind_a_comment_line(self):
        tests = read(os.path.join(self.rebuilt(), "tests.md"))
        self.assertTrue(tests.startswith("<!--"), tests[:80])
        self.assertIn("rebuilt", tests.split("-->", 1)[0])
        first, second = "## Validation 1: FAIL", "## Validation 2: PASS"
        self.assertIn(first, tests)
        self.assertIn(second, tests)
        self.assertLess(tests.index(first), tests.index(second))
        self.assertIn("| new_test | 1 |", tests)
        self.assertNotIn("Thanks, I will look", tests)
        self.assertNotIn("Review round", tests)

    def test_other_comments_are_numbered_in_posting_order(self):
        d = self.rebuilt()
        self.assertEqual(read(os.path.join(d, "comment-1.md")), CHATTER)
        self.assertEqual(read(os.path.join(d, "comment-2.md")), WITHHELD)

    def test_history_jsonl_holds_the_matching_rows_in_file_order(self):
        lines = read(os.path.join(self.rebuilt(), "history.jsonl")).splitlines()
        rows = [json.loads(ln) for ln in lines]
        self.assertEqual([r["rounds"] for r in rows], [1, 2])
        self.assertTrue(all(r["repo"] == "me/proj" for r in rows))
        self.assertTrue(all(r["branch"] == "feature/mul" for r in rows))

    def test_readme_names_the_source_and_what_is_missing(self):
        readme = read(os.path.join(self.rebuilt(), "README.md"))
        for needle in (
            "https://example.invalid/me/proj/pull/7",
            "Add mul",
            "feature/mul",
            "main",
            "2026-08-30T12:00:07Z",
            "c0ffee07",
            "tests/test_review_mul.py",
            "state.json",
            "logs",
            "| 1 | CHANGES_REQUESTED | claude-y | $1.20 |",
            "| 2 | APPROVE | claude-y | $0.80 |",
        ):
            self.assertIn(needle, readme, needle)
        self.assertNotIn("tests/test_calc.py", readme)
        self.assertNotIn("src/calc.py", readme)

    def test_every_file_is_lf_only(self):
        d = self.rebuilt()
        for name in os.listdir(d):
            text = read(os.path.join(d, name))
            self.assertNotIn("\r", text, name)
            self.assertTrue(text.endswith("\n"), name)

    def test_a_bare_pr_gets_no_tests_md_no_reviews_and_no_table(self):
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        d = self.dest("9-fix__plain")
        self.assertEqual(files_under(d), ["README.md", "change.md", "history.jsonl"])
        self.assertEqual(read(os.path.join(d, "change.md")), BODY_PLAIN)
        rows = [json.loads(ln) for ln in read(os.path.join(d, "history.jsonl")).splitlines()]
        self.assertEqual([r["branch"] for r in rows], ["fix/plain"])
        readme = read(os.path.join(d, "README.md"))
        self.assertNotIn("revali status", readme)
        self.assertNotIn("test_review_", readme)

    def test_no_history_file_at_all(self):
        os.remove(os.path.join(self.home, "history.jsonl"))
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertNotIn("history.jsonl", files_under(self.dest()))
        self.assertIn("review-1.md", files_under(self.dest()))


class Rerun(BackfillCase):
    """AC-3"""

    def test_an_archive_written_by_merge_survives(self):
        d = self.dest()
        os.makedirs(os.path.join(d, "logs"))
        # newline="": the fixture is read back with newline="" below; text mode would turn it
        # into CRLF on Windows and the assertion would blame the tool for the test's own file
        with open(os.path.join(d, "state.json"), "w", encoding="utf-8", newline="") as fh:
            fh.write('{"stage": "merged", "pr_number": 7}\n')
        with open(os.path.join(d, "logs", "revali.log"), "w", encoding="utf-8", newline="") as fh:
            fh.write("real\n")
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertEqual(files_under(d), ["logs/revali.log", "state.json"])
        state = read(os.path.join(d, "state.json"))
        self.assertEqual(state, '{"stage": "merged", "pr_number": 7}\n')
        lines = self.pr_lines(out, 7)
        self.assertEqual(len(lines), 1, out)
        self.assertIn("skipped", lines[0])
        self.assertTrue(os.path.isdir(self.dest("9-fix__plain")))  # the others still land

    def test_a_second_run_creates_nothing_and_exits_0(self):
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        before = {p: read(os.path.join(self.archive(), p)) for p in files_under(self.archive())}
        stamps = {p: os.path.getmtime(os.path.join(self.archive(), p)) for p in before}
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        after = {p: read(os.path.join(self.archive(), p)) for p in files_under(self.archive())}
        self.assertEqual(after, before)
        for p in before:
            self.assertEqual(os.path.getmtime(os.path.join(self.archive(), p)), stamps[p], p)
        for number in (7, 9):
            self.assertIn("skipped", "".join(self.pr_lines(out, number)), out)


class DryRun(BackfillCase):
    """AC-4"""

    def test_dry_run_prints_the_plan_and_writes_nothing(self):
        code, dry, err = self.run_tool("me/proj", "--dry-run")
        self.assertEqual(code, 0, err)
        self.assertFalse(os.path.exists(self.archive()))
        self.assertEqual(os.listdir(self.home), ["history.jsonl"])
        line7 = self.pr_lines(dry, 7)
        self.assertEqual(len(line7), 1, dry)
        self.assertIn(os.path.join("me__proj", "7-feature__mul"), line7[0])
        for name in ("review-1.md", "review-2.md", "tests.md", "history.jsonl", "comment-1.md"):
            self.assertIn(name, line7[0])
        code, wet, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        for number in (7, 8, 9):
            self.assertEqual(self.pr_lines(dry, number), self.pr_lines(wet, number))

    def test_dry_run_with_the_flag_creates_no_root_either(self):
        elsewhere = os.path.join(self.tmp, "nowhere yet")
        code, out, err = self.run_tool("me/proj", "--archive-dir", elsewhere, "--dry-run")
        self.assertEqual(code, 0, err)
        self.assertFalse(os.path.exists(elsewhere))


class Failures(BackfillCase):
    """AC-5"""

    def test_an_empty_root_exits_1_with_one_line_and_writes_nothing(self):
        self.user_config('[paths]\narchive_dir = ""\n')
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 1, out + err)
        self.assertEqual(len(err.strip().splitlines()), 1, err)
        self.assertNotIn("Traceback", err)
        self.assertIn("archive_dir", err)
        self.assertEqual(sorted(os.listdir(self.home)), ["config.toml", "history.jsonl"])
        code, out, err = self.run_tool("me/proj", "--archive-dir", os.path.join(self.tmp, "a b"))
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest(root=os.path.join(self.tmp, "a b"))))

    def test_a_failing_gh_exits_1_and_keeps_the_earlier_repository(self):
        self.prs(
            {
                "me/proj": [pr(7, "feature/mul", BODY_CRLF, [REVIEW_1])],
                "me/gone": {"fail": "GraphQL: Could not resolve to a Repository"},
            }
        )
        code, out, err = self.run_tool("me/proj", "me/gone")
        self.assertEqual(code, 1, out + err)
        self.assertEqual(len(err.strip().splitlines()), 1, err)
        self.assertNotIn("Traceback", err)
        self.assertIn("Could not resolve to a Repository", err)
        self.assertTrue(os.path.isfile(os.path.join(self.dest(), "review-1.md")))
        self.assertEqual(os.listdir(self.archive()), ["me__proj"])

    def test_a_failing_gh_on_the_first_repository_writes_nothing(self):
        good = [pr(7, "feature/mul", BODY_CRLF)]
        self.prs({"me/gone": {"fail": "HTTP 404"}, "me/proj": good})
        code, out, err = self.run_tool("me/gone", "me/proj")
        self.assertEqual(code, 1, out + err)
        self.assertIn("HTTP 404", err)
        self.assertFalse(os.path.exists(self.archive()))

    def test_a_gh_that_is_not_installed_exits_1_with_one_line(self):
        # no REVALI_GH_CMD and a PATH with nothing on it: resolve("gh") finds no executable
        empty = os.path.join(self.tmp, "empty path")
        os.makedirs(empty)
        env = dict(os.environ)
        env.pop("REVALI_GH_CMD", None)
        env["PATH"] = empty
        code, out, err = self.run_tool("me/proj", env=env)
        self.assertEqual(code, 1, out + err)
        self.assertEqual(len(err.strip().splitlines()), 1, err)
        self.assertNotIn("Traceback", err)
        self.assertIn("gh", err)
        self.assertFalse(os.path.exists(self.archive()))

    def test_a_listing_that_reaches_the_limit_is_refused_before_anything_is_written(self):
        # gh returns the newest PRs first and stops at --limit; a full page may hide the oldest
        # PRs, the ones a backfill is for. Three PRs in the fixture: --limit 3 fills the page.
        self.prs(
            {
                "me/first": [pr(1, "a/b", BODY_PLAIN)],
                "me/proj": self.default_prs(),
                "me/after": [pr(2, "c/d", BODY_PLAIN)],
            }
        )
        code, out, err = self.run_tool("me/first", "me/proj", "me/after", "--limit", "3")
        self.assertEqual(code, 1, out + err)
        self.assertEqual(len(err.strip().splitlines()), 1, err)
        self.assertNotIn("Traceback", err)
        self.assertIn("me/proj", err)
        self.assertIn("limit", err.lower())
        # the repository before it kept what it got; the failing one and the one after got nothing
        self.assertTrue(os.path.isdir(os.path.join(self.archive(), "me__first", "1-a__b")))
        self.assertEqual(os.listdir(self.archive()), ["me__first"])
        # one more than the page holds: the same listing is complete and accepted
        code, out, err = self.run_tool("me/proj", "--limit", "4")
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest()), out)
        self.assertTrue(os.path.isdir(self.dest("9-fix__plain")), out)

    def test_the_default_limit_is_not_reached_by_a_small_listing(self):
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertNotIn("limit", err.lower())


class History(BackfillCase):
    """AC-2 and AC-5: the history file is read the way revali reads it, and found where
    revali would look for it."""

    def test_a_line_that_does_not_parse_is_dropped_without_a_traceback(self):
        path = os.path.join(self.home, "history.jsonl")
        with open(path, "a", encoding="utf-8", newline="") as fh:
            fh.write('{"repo": "me/proj", "branch": "feature/mul", "stage": "merg\n')
            fh.write(json.dumps({"repo": "me/proj", "branch": "feature/mul", "rounds": 3}) + "\n")
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, out + err)
        self.assertNotIn("Traceback", err)
        lines = read(os.path.join(self.dest(), "history.jsonl")).splitlines()
        rows = [json.loads(ln) for ln in lines]
        self.assertEqual([r["rounds"] for r in rows], [1, 2, 3])
        # the other directories of the repository were written too
        self.assertTrue(os.path.isdir(self.dest("9-fix__plain")))

    def test_the_users_history_path_is_read(self):
        moved = os.path.join(self.tmp, "runs elsewhere.jsonl")
        os.replace(os.path.join(self.home, "history.jsonl"), moved)
        self.user_config("history_path = %s\n" % json.dumps(moved.replace("\\", "/")))
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        lines = read(os.path.join(self.dest(), "history.jsonl")).splitlines()
        self.assertEqual([json.loads(ln)["rounds"] for ln in lines], [1, 2])

    def test_the_users_history_file_name_is_read(self):
        os.replace(
            os.path.join(self.home, "history.jsonl"), os.path.join(self.home, "renamed.jsonl")
        )
        self.user_config('[paths]\nhistory_file = "renamed.jsonl"\n')
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertIn("history.jsonl", files_under(self.dest()))
        lines = read(os.path.join(self.dest(), "history.jsonl")).splitlines()
        self.assertEqual([json.loads(ln)["rounds"] for ln in lines], [1, 2])


class RootResolution(BackfillCase):
    """AC-1: defaults, then the user file; a project file has no say."""

    def test_a_revali_toml_in_the_working_directory_does_not_move_the_root(self):
        with open(os.path.join(self.tmp, "revali.toml"), "w", encoding="utf-8", newline="") as fh:
            fh.write('[paths]\narchive_dir = "from-project"\n')
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest()), out)
        self.assertFalse(os.path.exists(os.path.join(self.home, "from-project")))
        self.assertFalse(os.path.exists(os.path.join(self.tmp, "from-project")))

    def test_a_tilde_in_the_user_value_is_expanded(self):
        fake_home = os.path.join(self.tmp, "fake home")
        os.makedirs(fake_home)
        env = dict(os.environ)
        env["HOME"] = fake_home
        env["USERPROFILE"] = fake_home
        self.user_config('[paths]\narchive_dir = "~/kept"\n')
        code, out, err = self.run_tool("me/proj", env=env)
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest(root=os.path.join(fake_home, "kept"))), out)
        self.assertFalse(os.path.isdir(self.archive()))


class Suffixed(BackfillCase):
    """AC-3: the directory `merge` wrote for the same PR, under the `-<YYYYMMDD-HHMMSS>` suffix
    it adds to a taken name, is the archive of that PR and is not rebuilt beside."""

    def test_a_suffixed_archive_written_by_merge_counts_as_existing(self):
        suffixed = self.dest() + "-20260907-120000"
        os.makedirs(suffixed)
        with open(os.path.join(suffixed, "state.json"), "w", encoding="utf-8", newline="") as fh:
            fh.write("{}\n")
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertFalse(os.path.exists(self.dest()), out)
        self.assertEqual(os.listdir(suffixed), ["state.json"])
        lines = self.pr_lines(out, 7)
        self.assertEqual(len(lines), 1, out)
        self.assertIn("skipped", lines[0])
        self.assertTrue(os.path.isdir(self.dest("9-fix__plain")))

    def test_another_prs_directory_with_the_same_prefix_digits_is_not_confused(self):
        # PR 70's directory starts with "7" but is not PR 7's
        os.makedirs(self.dest("70-feature__mul"))
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, err)
        self.assertTrue(os.path.isdir(self.dest()), out)


class DuplicateRound(BackfillCase):
    """AC-2: two comments for one round (a retried post) still give one review-<n>.md."""

    def test_the_later_comment_is_kept_and_the_run_says_so(self):
        retry = REVIEW_1.replace("The product is off by one.", "Posted again after a timeout.")
        self.prs({"me/proj": [pr(7, "feature/mul", BODY_CRLF, [REVIEW_1, CHATTER, retry])]})
        code, out, err = self.run_tool("me/proj")
        self.assertEqual(code, 0, out + err)
        self.assertNotIn("Traceback", err)
        d = self.dest()
        expected = ["README.md", "change.md", "comment-1.md", "history.jsonl", "review-1.md"]
        self.assertEqual(files_under(d), expected)
        self.assertEqual(read(os.path.join(d, "review-1.md")), retry)
        self.assertIn("review-1.md", "".join(self.pr_lines(out, 7)))


class Dependencies(unittest.TestCase):
    """AC-6: the import list; the README and docs wording is documentation."""

    def test_the_script_imports_only_stdlib_and_revali(self):
        tree = ast.parse(read(SCRIPT))
        names = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names.update(alias.name.split(".")[0] for alias in node.names)
            elif isinstance(node, ast.ImportFrom):
                names.add((node.module or "").split(".")[0])
        foreign = sorted(n for n in names if n != "revali" and n not in sys.stdlib_module_names)
        self.assertEqual(foreign, [])


if __name__ == "__main__":
    unittest.main()
